// SeaAreas.java
// 15th april 2024

public enum SeaAreas {
    ARABIAN_SEA,
    ARCTIC_OCEAN,
    ANTARCTIC_OCEAN,
    ATLANTIC_OCEAN,
    BERING_SEA,
    CARIBBEAN_SEA,
    CORAL_SEA,
    EAST_CHINA_SEA,
    GULF_OF_MEXICO,
    HUDSON_BAY,
    INDIAN_OCEAN,
    MEDITERRANEAN_SEA,
    NORTH_ATLANTIC_OCEAN,
    NORTH_PACIFIC_OCEAN,
    PACIFIC_OCEAN,
    PHILIPPINE_SEA,
    SARGASSO_SEA,
    SOUTH_ATLANTIC_OCEAN,
    SOUTH_CHINA_SEA,
    SOUTH_PACIFIC_OCEAN,
    SOUTHERN_OCEAN,
    WEDDELL_SEA,
}